### ISSUE TITLE
Remote URL for downloading ICON hsurf file appears to be missing the time interval. 

### ISSUE THREAD

**Issue by winash12** [guidocioni/icon_globe#1]
I cloned your git repository to a local directory on my Ubuntu installation and ran the script copy_data.run and I think the  URL to download is missing the time information such as 00, 06, 12 , 18 .

This appears to be the URL - https://opendata.dwd.de/weather/nwp/icon/grib/00/hsurf/

Please take a look at the screenshot below . 

![Screenshot from 2022-11-24 16-11-53](https://user-images.githubusercontent.com/9129700/203764233-96844796-10a9-44f4-ac5a-6060f6cd31c1.png)

Would you be willing to accept a pull request or is there a mistake in my running the script ?

**Comment by guidocioni** [comment]
Hey @winash12, thanks for describing the issue clearly. 

The problem is that the link for every variable (not just for `HSURF`) is created dynamically based on the run that is processed at that time.
As explained in the README for the EU version (https://github.com/guidocioni/icon_forecasts), in order to decide which run to process, a Python script (`get_last_run.py`) is called to determine the latest run on the server. If this is newer than the run processed locally (this is determined using a 'semaphore' file, `last_processed_run.txt`) then the script proceeds to process that run.

As you can see in your log you don't have any `python` executable installed, which means that this line here https://github.com/guidocioni/icon_globe/blob/6ac14783183ecd7f91e25674d0ac999933dc4287/copy_data.run#L29 returns nothing and the run here https://github.com/guidocioni/icon_globe/blob/6ac14783183ecd7f91e25674d0ac999933dc4287/copy_data.run#L40 is not parsed, so you have empty string for every part of the run.
This explains why you don't have any string for the run when getting `HSURF`. 

You have two solutions: either install `python` with the relevant packages and leave the script like this: this mechanism is useful if you want to always process the most recent run from the server.  Or you can just "remove" this feature and just decide the run yourself based on the time of day (something similar to this https://github.com/guidocioni/gens/blob/1761d0f283844105c5a6deff798e5a4c1308bb44/get_grib.run#L42, but you'll have to define your own rules). I used to use something similar for ICON but then I just found this "dynamic" way easier to handle. 

I'm sorry this is not better documented, I never thought this package was going to be used by so many people :D

**Comment by winash12** [comment]
@guidocioni Thanks for the latest response. I do have python installed on my system. There isn't an executable python but the python is installed as python3.8 or python3.7. I can search and replace python with python3.8. Would that work ?

Secondly the git clone to my local dir did not download the file get_last_run.py.  I had to physically download the file myself.

I hope what I am reporting is useful for others. Because if I can get your code to work on my box and then I can check it in to my github site others can use it with some modifications perhaps.

**Comment by guidocioni** [comment]
> @guidocioni Thanks for the latest response. I do have python installed on my system. There isn't an executable python but the python is installed as python3.8 or python3.7. I can search and replace python with python3.8. Would that work ?
> 

Then there is something wrong in the environment because you can see in your log that `python` is not found as command (`Line 29, python not found`). 
You have to make sure that the python executable is linked to `python` when it is called. If it doesn't work a solution that usually helps is to re-define python in your script as variable,
```bash
export python=/path/to/your/python/executable
``` 
and then replace all occurrences of `python` with `${python}` in `copy_data.run`.

> Secondly the git clone to my local dir did not download the file get_last_run.py. I had to physically download the file myself.
> 

Not sure why, if it is in the repository it should be also downloaded when you clone it. Maybe it was deleted by accident. You can always check with `git status`. That file is indeed in the repo, otherwise you won't even be able to see it on github. 

> I hope what I am reporting is useful for others. Because if I can get your code to work on my box and then I can check it in to my github site others can use it with some modifications perhaps.

It will take a while probably, this code is a mess and not really easy to set up. I just maintain it for my own machine so I understand it will be hard for someone to set it for the first time given the huge amount of dependencies and resources needed. But you're free to try it :)

**Comment by winash12** [comment]
Much better after the python environmental variable substitutions. I removed the ncftp code because I am not planning to upload my  plots anywhere. Just focusing on getting the download data going. I commented out the plotting as well. 

It is downloading some data but the files are empty and after the script finish executing the files disappear.  Also it is looking for some robots.txt file and I am not sure what it is.

No rush on getting back to me. Whenever possible please feel free to reply to this thread.  


![Screenshot from 2022-11-24 18-08-52](https://user-images.githubusercontent.com/9129700/203786635-2bb01e81-3f28-4284-b9f5-2e9ff07caefb.png)

**Comment by guidocioni** [comment]
You can ignore those errors. Everything looks fine to me.
The bz2 are downloaded, then extracted and then there is some merging going on, that's why you see them disappear maybe. You have to dig deeper into the downloading functions if you want to change the behaviour.
